{% set name = "fermitools-data" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/fermitools-data.git

build:
  number: 0
  noarch: generic
